webapp/forms/addPost.py
from wtforms import  StringField, TextAreaField, SubmitField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from flask_wtf.file import FileField
from flask_ckeditor import CKEditorField


class AddPostForm (FlaskForm):
    heading = StringField("Enter Heading: ", validators=[DataRequired()])
    postImage = FileField("Enter Image: ", validators=[DataRequired()])
    postContent = CKEditorField("Enter Post: ", validators=[DataRequired()])
    submit = SubmitField()

webapp/forms/loginForm.py
from wtforms import  StringField,SubmitField, PasswordField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    email = StringField("Enter Email: ", validators=[DataRequired()])
    password = PasswordField("Enter Password: ", validators=[DataRequired()])
    submit = SubmitField("Login")

webapp/forms/registerForm.py
from wtforms import  StringField,SubmitField, PasswordField
from wtforms.validators import DataRequired, EqualTo
from .loginForm import LoginForm
from flask_wtf.file import FileField

class RegisterForm(LoginForm):
    name = StringField("Enter Full Name: ", validators=[DataRequired()])
    userImage = FileField("Upload Profile Image: ", validators=[DataRequired()])
    confirmPassword = PasswordField("Confirm Password: ", validators=[DataRequired(),EqualTo('password', message='Both Password and Confirm Password must match')])
    submit = SubmitField("Register")

webapp/views/adminViews.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login.utils import login_required
from ..utils.adminDecorator import admin_protected
from ..models import Post
from .. import db

adminviews = Blueprint('adminviews', __name__)


@adminviews.route("/")
@login_required
@admin_protected
def home():
    unapprovedPosts = db.session.query(Post).filter_by(isApproved=False).all()
    return render_template("adminAccount.html", unapprovedPosts=unapprovedPosts)


@adminviews.route("/approve/<postid>")
@login_required
@admin_protected
def approvepost(postid):
    post = db.session.query(Post).filter_by(id=postid).first()
    post.isApproved = True
    db.session.commit()
    return redirect(url_for("adminviews.home"))

webapp/views/authviews.py
from flask import Blueprint, render_template,request, redirect, url_for, flash
from flask_login.utils import login_required
from ..utils.fileUploader import FileUploader
from ..models import User
from ..forms.loginForm import LoginForm
from ..forms.registerForm import RegisterForm
from .. import db
import bcrypt
from flask_login import login_user, current_user, logout_user

authviews = Blueprint('authviews', __name__)

@authviews.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm() 
    
    if request.method == "POST" and form.validate_on_submit(): 
        name = form.name.data
        email = form.email.data
        userImage = form.userImage.data 
        password = form.password.data
        confirmPw = form.confirmPassword.data 


        if password == confirmPw:
            fileuploader = FileUploader(userImage)
            
            if fileuploader.isImage():
                uploadedUrl = fileuploader.uploadToCloudinary()
            
            else:
                flash("Your uploaded image format is not supported!", category="error")
                return redirect(url_for("authviews.register"))

            hashedPassword = bcrypt.hashpw(password=password.encode('utf-8'), salt=bcrypt.gensalt(12))
            hashedPassword = hashedPassword.decode('utf-8')
            newUser = User(username=name, email=email, password=hashedPassword, profilePicture=uploadedUrl)
            db.session.add(newUser)
            db.session.commit()
            return redirect(url_for("authviews.login")) 

        else:
            return "Something went wrong!"

    return render_template("register.html", form=form)


@authviews.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if request.method == "POST" and form.validate_on_submit():
        email = form.email.data
        password = form.password.data 

        userExist = db.session.query(User).filter_by(email=email).count()

        if userExist > 0:
            user = db.session.query(User).filter_by(email=email).first() 

            try:
                if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                    login_user(user=user, remember=True)
                    return redirect(url_for("blogviews.home"))

            except ValueError:
                    flash("Your username or password is incorrect!", category="error")
                    return redirect(url_for("authviews.login"))

        else:
            flash("We coundn't find your account! Create an account if you are not registered!", category="error")
            return redirect(url_for("authviews.login"))

    return render_template("login.html", form=form)


@authviews.route("/myaccount")
@login_required
def myaccount():
    return render_template("myaccount.html")


@authviews.route("/logout", methods=["GET"])
def logout():
    logout_user()
    return redirect(url_for("authviews.login")) 

webapp/views/blogviews.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import desc
from webapp.forms.addPost import AddPostForm 
from ..utils.fileUploader import FileUploader
from .. import db
# from ..models.post import Post
from ..models import Post, Comment

blogviews = Blueprint('blogviews', __name__)


@blogviews.route("/")
def home():
    topRatedPosts = db.session.query(Post).filter_by(isApproved=True).order_by(desc(Post.views)).limit(6).all()
    newPosts = db.session.query(Post).filter_by(isApproved=True).order_by(desc(Post.publishedDate)).limit(12).all()
    return render_template("index.html", topRatedPosts=topRatedPosts, newPosts=newPosts)


@blogviews.route("/posts")
def viewAllPosts():
    posts = db.session.query(Post).all()
    return render_template("allPosts.html", posts=posts)



@blogviews.route("/post/<postid>/<postname>")
@login_required
def viewPost(postid, postname):
    if not postid or not postname:
        return redirect(url_for("blogviews.home"))
    selectedPost = db.session.query(Post).filter_by(id=postid).first()
    selectedPost.views += 1
    db.session.commit()
    readTime = round(len(selectedPost.postBody.split()) / 250)
    if(readTime == 0):
        readTime = 1

    return render_template("post.html", post=selectedPost, readTime=readTime)


@blogviews.route("/add-post", methods=["GET", "POST"])
@login_required
def addPost():
    form = AddPostForm() 
    if request.method == 'POST' and form.validate_on_submit():
        postHeading = form.heading.data
        image = form.postImage.data
        postBody = form.postContent.data
         
        fileUploader = FileUploader(image) 

        if(fileUploader.isImage()):
            uploadedUrl = fileUploader.uploadToCloudinary()

        if fileUploader.isUploaded:
            newPost = Post(headline=postHeading, image=uploadedUrl, postBody=postBody, user_id=current_user.get_id())
            db.session.add(newPost)
            db.session.commit()
            return redirect(url_for("blogviews.home"))

        else:
            return "Something went wrong!" 
        
    return render_template("addPost.html", form=form)


@blogviews.route("/comment/<postid>/<postname>", methods=["POST"])
@login_required
def addComment(postid,postname):
    comment = request.form.get("comment")
    newComment = Comment(comment_body=comment, post_id=postid, user_id=current_user.get_id())
    db.session.add(newComment)
    db.session.commit()
    return redirect(url_for('blogviews.viewPost', postid=postid, postname=postname.replace(' ', '-')))

@blogviews.route("/post/delete/<postid>", methods=["GET", "POST"])
@login_required
def deletePost(postid):
    postToDelete = db.session.query(Post).filter_by(id=postid).first()
    publicID = 'WeirdDiary/uploads/' + postToDelete.image.rsplit('/', 1)[-1].rsplit(".")[0]
    FileUploader.deleteFileFromCloudinary(publicid=publicID)
    db.session.query(Post).filter_by(id=postid).delete()
    db.session.commit()
    return redirect(url_for("authviews.myaccount"))

webapp/templates/addPost.html
{% extends "baseLayout.html" %} {% block stylesheet %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/index.css') }}"
/>

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/login.css') }}"
/>

{% endblock %} {% block title %} Weird Diary - Write new post {% endblock %}
{%block pageContent%}

<div class="post-page-content">
  <div class="authentication-form">
    <form
      action="{{ url_for('blogviews.addPost') }}"
      novalidate
      method="POST"
      enctype="multipart/form-data"
    >
      <h1 style="text-align: center">Post a new post</h1>

      {{ form.hidden_tag() }}

      <div class="input">
        <label for="email">{{ form.heading.label() }} </label>

        {% for err in form.heading.errors %}
        <small class="error-msg">{{ err }}</small>
        {% endfor %} {{ form.heading() }}
      </div>

      <div class="input">
        <label for="email">{{ form.postImage.label() }} </label>
        {% for err in form.postImage.errors %}
        <small class="error-msg">{{ err }}</small>
        {% endfor %} {{form.postImage(id="image-upload")}}
        <i id="image-upload-icon" class="fa-solid fa-cloud-arrow-up"> </i>
        <p class="uploaded-file-text"></p>
      </div>

      <div class="input">
        <label for="password">{{ form.postContent.label() }} </label>

        {% for err in form.postContent.errors %}
        <small class="error-msg">{{ err }}</small>
        {% endfor %} {{form.postContent(rows=10, class="postBodyInput")}}
      </div>

      {{ ckeditor.load() }} {{form.submit(class="authformsubmit-btn")}}
    </form>
  </div>
</div>
{% endblock %}

webapp/templates/adminAccount.html
{% extends "baseLayout.html" %} {% block stylesheet %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/index.css') }}"
/>

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/myaccount.css') }}"
/>

{% endblock %} {% block title %} Weird Diary - Admin {% endblock %}
{%block pageContent%}

<div class="myaccount-page-content">
  <div class="myaccount">
    <div class="articles-published" style="overflow-x: auto">
      <h1>Admin Panel</h1>
      <h2>Posts to approve</h2>
      <div>
        <table>
          <tr>
            <th>Post Heading</th>
            <th>Published Date</th>
            <th>Status</th>
          </tr>

          {% for post in unapprovedPosts %}

          <tr>
            <td>{{post.headline}}</td>
            <td>{{post.publishedDate.strftime('%Y-%m-%d')}}</td>
            <td>
            {% if post.isApproved %}
              Published
            {%else%}
              Pending
            {% endif %}
            </td>
            <td>
              <a href="{{ url_for('adminviews.approvepost', postid=post.id) }}">
                <i class="fa-solid fa-circle-check" style="font-size: 23px; color: rgb(1, 161, 1); cursor: pointer;"></i>
              </a>

              <a href="{{ url_for('blogviews.deletePost', postid=post.id) }}">
                <i class="fa-solid fa-circle-xmark" style="margin-left: 10px; font-size: 23px; color: rgb(255, 72, 72);cursor: pointer;"></i>
              </a>
            </td>
          </tr>

          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}

webapp/templates/adminPosts.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Source+Sans+Pro:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
      integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.css"
    />
    <title>Welcome to Weird Diary</title>
    <link rel="stylesheet" href="./css/index.css" />
    <link rel="stylesheet" href="./css/myaccount.css" />
  </head>
  <body>
    <div class="navbar-container">
      <nav>
        <div class="logo">
          <img src="./images/ClipartKey_2603740.png" alt="" />
          <h3>WEIRD DIARY</h3>
        </div>

        <div class="nav-items">
          <ul>
            <li>
              <i id="darkmode-toggle" class="fa-regular fa-sun"></i>
            </li>
            <li class="nav-account">
              <div class="nav-account-container">
                <img src="./images/image.jpg" alt="Weird Diary User" />
                <div>
                  <p>John Doe</p>
                  <p>johndoe@gmail.com</p>
                </div>
              </div>
            </li>

            <li>Login</li>
            <li>Contact us</li>
            <li>About Us</li>
            <li><i class="fa-solid fa-1x fa-magnifying-glass"></i></li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="myaccount-page-content">
      <div class="myaccount">
        <div class="articles-published">
          <h1>Admin Panel</h1>
          <h2>All Posts Available</h2>
          <div>
            <table>
              <tr>
                <th>Post ID</th>
                <th>Post Name</th>
                <th></th>
              </tr>
              <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>
                  <div>
                    <button class="approve-btn">Approve</button>
                    <button class="deny-btn">Deny</button>
                  </div>
                </td>
              </tr>
              <tr>
                <td>Centro comercial Moctezuma</td>
                <td>Francisco Chang</td>
                <td>
                  <div>
                    <button class="approve-btn">Approve</button>
                    <button class="deny-btn">Deny</button>
                  </div>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>

    <footer>
      <div class="footer">
        <div class="footer_main">
          <h3>Quick Start</h3>
          <ul>
            <li>All Posts</li>
            <li>Contact Us</li>
            <li>About Us</li>
            <li>Newsletter</li>
          </ul>
        </div>
        <div class="footer_main">
          <h3>About Payment</h3>
          <ul>
            <li>Payments</li>
            <li>Refunds</li>
            <li>Privacy Policy</li>
            <li>Newsletter</li>
          </ul>
        </div>

        <div class="footer_right">
          <div class="footer_links">
            <i
              style="color: rgb(25, 0, 255)"
              class="fa-brands fa-facebook fa-2x"
            ></i>
            <i
              style="color: rgb(54, 32, 255)"
              class="fa-brands fa-twitter fa-2x"
            ></i>
            <i
              style="color: rgb(121, 0, 0)"
              class="fa-brands fa-pinterest fa-2x"
            ></i>
            <i
              style="color: rgb(0, 97, 40)"
              class="fa-brands fa-whatsapp fa-2x"
            ></i>
          </div>
        </div>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
      integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
      crossorigin="anonymous"
    ></script>
    <script src="./js/slider.js"></script>
    <script src="./js/darkModeScript.js"></script>
  </body>
</html>

webapp/templates/allPosts.html
{% extends "baseLayout.html" %} {% block stylesheet %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/index.css') }}"
/>

{% endblock %} {% block title %} Welcome to Weird Diary {% endblock %} {%block
pageContent%}
<div class="page-content">
  <h1 class="main-title"></h1>

  <div class="top-post-conatiner">
    {% for post in posts %}
    <div class="top-post-card">
      <img src="{{ post.image }}" alt="" />

      <h3>
        <a
          href="{{ url_for('blogviews.viewPost', postid=post.id, postname=post.headline.replace(' ', '-')) }}"
        >
          {{ post.headline[0:27] }}...
        </a>
      </h3>

      <p class="card-description">{{ post.postBody[0:80] | striptags }}...</p>

      <div class="post-card-user">
        <img src="{{ post.user.profilePicture }}" alt="" />
        <div>
          <small>{{ post.user.username }}</small> <br />
          <small>{{ post.user.email }}</small>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>
{% endblock %}

webapp/templates/baseLayout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Source+Sans+Pro:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
      integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='images/favicon.ico') }}"
    />

    {% block stylesheet %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="navbar-container">
      <nav>
        <a href="{{ url_for('blogviews.home') }}">
          <div class="logo">
            <img
              src="https://res.cloudinary.com/dxrksxul/image/upload/v1636094963/WeirdDiary/static/ClipartKey_2603740_jgxgim.png"
              alt="Weird Diary Logo"
            />
            <h3>WEIRD DIARY</h3>
          </div>
        </a>

        <div class="hamburger-container">
          <i class="hamburger-icon fa-solid fa-bars fa-2x"></i>
        </div>

        <div class="nav-items">
          <ul>
            <li>
              <i id="darkmode-toggle" class="fa-regular fa-sun"></i>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-account">
              <a href="{{ url_for('authviews.myaccount') }}">
                <div class="nav-account-container">
                  <img
                    src="{{current_user.profilePicture}}"
                    alt="{{current_user.username}}"
                  />
                  <div>
                    <p>{{current_user.username}}</p>
                    <p>{{current_user.email}}</p>
                  </div>
                </div>
              </a>
            </li>
            {% endif %} {% if current_user.is_authenticated %}
            <a href="{{ url_for('authviews.logout') }}">
              <li>Logout</li>
            </a>
            {% else %}
            <a href="{{ url_for('authviews.login') }}">
              <li>Login</li>
            </a>
            {% endif %}

            <a href="{{ url_for('blogviews.viewAllPosts') }}">
              <li>All Posts</li>
            </a>
            <li>Contact us</li>
            <li>About Us</li>
          </ul>
        </div>
      </nav>
    </div>

    {%block pageContent%} {% endblock %}

    <footer>
      <div class="footer">
        <div class="footer_main">
          <h3>Quick Start</h3>
          <ul>
            <li>All Posts</li>
            <li>Contact Us</li>
            <li>About Us</li>
            <li>Newsletter</li>
          </ul>
        </div>
        <div class="footer_main">
          <h3>About Payment</h3>
          <ul>
            <li>Payments</li>
            <li>Refunds</li>
            <li>Privacy Policy</li>
            <li>Newsletter</li>
          </ul>
        </div>

        <div class="footer_right">
          <div class="footer_links">
            <i
              style="color: rgb(25, 0, 255)"
              class="fa-brands fa-facebook fa-2x"
            ></i>
            <i
              style="color: rgb(54, 32, 255)"
              class="fa-brands fa-twitter fa-2x"
            ></i>
            <i
              style="color: rgb(121, 0, 0)"
              class="fa-brands fa-pinterest fa-2x"
            ></i>
            <i
              style="color: rgb(0, 97, 40)"
              class="fa-brands fa-whatsapp fa-2x"
            ></i>
          </div>
        </div>
      </div>
    </footer>
    <script
      src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
      integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
      crossorigin="anonymous"
    ></script>
    <script
      src="{{ url_for('static', filename='js/darkModeScript.js') }}"
      defer
    ></script>
    <script
      src="{{ url_for('static', filename='js/index.js') }}"
      defer
    ></script>
  </body>
</html>

webapp/templates/index.html
{% extends "baseLayout.html" %} {% block stylesheet %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/index.css') }}"
/>

{% endblock %} {% block title %} Welcome to Weird Diary {% endblock %} {%block
pageContent%}
<div class="page-content">
  <!-- Slider -->
  <div class="landing-background">
    <h1 class="landing-intro">Welcome to Weird Diary</h1>
    <p class="landing-intro">Share your stories!</p>
  </div>

  <h1 class="main-title">This Week's Top Posts</h1>

  <div class="top-post-conatiner">
    {% for topRatedPost in topRatedPosts %}
    <div class="top-post-card">
      <img src="{{ topRatedPost.image }}" alt="" />

      <h3>
        <a
          href="{{ url_for('blogviews.viewPost', postid=topRatedPost.id, postname=topRatedPost.headline.replace(' ', '-')) }}"
        >
          {{ topRatedPost.headline[0:27] }}...
        </a>
      </h3>

      <div class="card-description">
        {{ topRatedPost.postBody[0:80] | striptags }}...
      </div>

      <div class="post-card-user">
        <img src="{{ topRatedPost.user.profilePicture }}" alt="" />
        <div>
          <small>{{ topRatedPost.user.username }}</small> <br />
          <small>{{ topRatedPost.user.email }}</small>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>

  <h1 class="main-title">Newest Posts</h1>

  <div class="newest-posts-container">
    {% for post in newPosts %}
    <a
      href="{{ url_for('blogviews.viewPost', postid=post.id, postname=post.headline.replace(' ', '-')) }}"
    >
      <div class="newest-posts-card">
        <div>
          <img src="{{ post.image }}" alt="" />
        </div>

        <div class="newest-post-details">
          <h3>{{post.headline[0:27]}}...</h3>
          <p>{{post.views}} Views</p>
          <small>{{post.publishedDate.strftime('%Y-%m-%d')}}</small>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

webapp/templates/myaccount.html
{% extends "baseLayout.html" %} {% block stylesheet %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/index.css') }}"
/>

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/myaccount.css') }}"
/>

{% endblock %} {% block title %} {{current_user.username}} - Weird Diary {%
endblock %} {%block pageContent%}
<div class="myaccount-page-content">
  <div class="myaccount">
    <div class="account-info">
      <div class="user-account-info">
        <img
          src="{{current_user.profilePicture}}"
          alt="{{current_user.username}}"
        />

        <div class="user-infomation">
          <p>{{current_user.username}}</p>
          <p>{{current_user.email}}</p>
        </div>

        <div class="myaccount-button-container">
          <a href="{{ url_for('authviews.logout') }}">
            <button class="my-account-delete-buttons">Logout</button>
          </a>

          <a href="{{ url_for('blogviews.addPost') }}">
            <button class="my-account-delete-buttons">Write a post</button>
          </a>

          {% if current_user.role.lower() == "Admin".lower() %}
          <a href="{{ url_for('adminviews.home') }}">
            <button class="my-account-delete-buttons">Admin Area</button>
          </a>
          {% endif %}
        </div>
      </div>
    </div>

    {% if current_user.posts | length > 0 %}
    <div class="articles-published">
      <h2>Post Published</h2>
      <div>
        <table>
          <tr>
            <th>Post ID</th>
            <th>Post Heading</th>
            <th>Status</th>
            <th></th>
          </tr>

          {% for post in current_user.posts %}
          <tr>
            <td>{{ post.id }}</td>
            <td>{{ post.headline }}</td>
            <td>
              {% if post.isApproved %} Published {%else%} Pending {% endif %}
            </td>
            <th>
              <div class="post-action-column">
                <div>
                  <form
                    onSubmit="return alert('This functionality will be available soon');"
                    method="get"
                  >
                    <button
                      type="submit"
                      class="deny-btn edit-btn"
                      value="{{post.id}}"
                    >
                      Edit
                    </button>
                  </form>
                </div>

                <div>
                  <form
                    action="{{ url_for('blogviews.deletePost', postid=post.id) }}"
                    onSubmit="return confirm('Are you sure you wish to delete?');"
                    method="get"
                  >
                    <button type="submit" class="deny-btn" value="{{post.id}}">
                      Delete
                    </button>
                  </form>
                </div>
              </div>
            </th>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>

    {% endif %}
  </div>
</div>

{% endblock %}

webapp/templates/post.html
{% extends "baseLayout.html" %} {% block stylesheet %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/index.css') }}"
/>

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/postpage.css') }}"
/>

{% endblock %} {% block title %} {{ post.headline }} - Weird Diary {% endblock
%} {%block pageContent%}

<div class="post-page-content">
  <div class="post-area">
    <img class="post-cover" src="{{ post.image }}" />

    <div class="user-area">
      <img class="profile-pic" src="{{post.user.profilePicture}}" />

      <div class="user-info">
        <h3>Author: {{ post.user.username }}</h3>
        <p>{{ post.user.email }}</p>
      </div>
    </div>

    <p>{{post.views}} views | {{readTime}}min Reading</p>

    <h1 class="post-headline">{{post.headline}}</h1>

    <div class="post-content">{{post.postBody | safe}}</div>

    <hr class="post-end" />

    <div class="comments-area">
      <h3>Comments ({{post.comments | length}})</h3>

      {% for comment in post.comments %}
      <div class="comment">
        <div class="user-area comment-user-area">
          <img class="profile-pic" src="{{comment.user.profilePicture}}" />

          <div class="user-info">
            <h5>{{comment.user.username}}</h5>
            <small>{{comment.user.email}}</small>
          </div>
        </div>

        <p>{{comment.comment_body}}</p>
      </div>
      {% endfor %}

      <form
        action="{{ url_for('blogviews.addComment', postid=post.id, postname=post.headline) }}"
        method="post"
      >
        <h3>Enter your comment here...</h3>
        <textarea class="comment-type-area" name="comment"></textarea>
        <button class="comment-submit-button">Comment</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}